theme = "hugo-sustain"

baseURL = "https://geonnave.github.io/"
languageCode = "en-us"
title = "blogeo"

disqusShortname = "geonnave"
googleAnalytics = "UA-117079100-1"

pygmentsCodeFences = true
pygmentsStyle = "manni"

## Site Settings
[params]
    author = "Geovane Fedrecheski"
    description = "software & other stories"
    authorimage = "/img/geovane.jpg"
    avatar = "/geovane.jpg"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    themeColor = "theme-base-08"
    # highlightjsstyle = "github"
    # please choose either GraphComment or Disqus
    # GraphCommentId = "your-graph-comment-id"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[taxonomies]
   tag = "tags"
   category = "categories"

## Social Accounts
[params.social]
    github = "geonnave"
    linkedin = "geovane-fedrecheski"
    twitter = "geonnave"
    email = "geonnave@gmail.com"

[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "Projects"
    identifier = "projects"
    weight = 200
    url = "/projects/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
